### PR TITLE
Adding backend sources for SDL3

### PR DESCRIPTION
**Pull request by dmikushin**
This PR experimentally adds backend files for SDL3. 

SDL3 only differs from SDL2 in some functions/enums naming and a few function arguments. Nonetheless, this PR creates separate files for SDL3 for more clearance.

I'd appreciate devs' advise what would be your preference about removing SDL2/SDL3 code deduplication. One option that I see is to use:

```c++
#if SDL_VERSION_ATLEAST(3, 0, 0)
```

What do you think?

### CODE REVIEW

**Comment by mikke89** [comment]
Very cool, thank you!

I am already feeling the maintenance overhead of all the backends, so it would be preferable if we could unite them. Especially considering that it's not just the SDL_SDLrenderer backend, but the GL ones too. It quickly becomes a combinatorial problem. We probably need some preprocessing like you suggest. Though, I think I'd prefer we use `SDL_MAJOR_VERSION`.

I see that they've done some work on the their high DPI support, finally! It would be really cool if we could add support for that, similar to how we do it in GLFW.

**Comment by mikke89** [comment]
Hey, do you have an update on this one? Would be great to see this being continued.

**Comment by dmikushin** [comment]
Hi @mikke89 , not yet, I've been developing some RmlUi app that shall also work as a test bed for this SDL 3.0 work. I plan to finish it, make sure no issues originate from this context, and then - clean up this PR according to your preference expressed above. Alternatively, I can refactor the PR right away, but that would be a blind shot, no real testing at all. What do you think?

**Comment by mikke89** [comment]
Cool, I'd be interested to hear more about the project of yours.

There's no hurry, but I wouldn't mind merging something not fully tested, as long as we don't have any regression for SDL2. And I'll of course help test for any such regressions. Then we can do a follow-up pull request for more polishing later on. This way other users can more easily test and help out too as they spot things.

**Comment by mikke89** [comment]
Hey, I have added SDL 3 support to all our existing SDL backends now: 01fc3c40aa6f4886d89aa3f9762d9aeb4e4d8625

Also, they made some nice improvements to the high DPI support in SDL 3, so I went ahead and added support for that too: 56d1a21c5ca2c799e1a3540f1d6fc11e613f16ff :)

Closing this PR as it has been replaced by the above two commits. Thanks for the contribution though! If you have some ideas to improve the backends or SDL 3 support particularly, feel free to make a new PR.

**Pull request closed without merging**
