### PR TITLE
feat(cmake): disable export targets when rmlui as a subproject

### PR DESCRIPTION
**Pull request by cathaysia**
Signed-off-by: Longtao Zhang <DragonBillow@outlook.com>

### CODE REVIEW

**Comment by cathaysia** [comment]
sorry, please wait for a while

**Comment by cathaysia** [comment]
add a .editorconf is better, such as:

```ini
# EditorConfig is awesome: https://EditorConfig.org
root = true

[*]
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
charset = utf-8
indent_style = tab
indent_size = 4
```

**Comment by mikke89** [comment]
Thanks again!

We already have a clang-format for C++ files, I don't think one is needed for CMake specifically. Generally, editors should be setup to follow the existing style of the file, then it usually turns out correct.

**Comment by cathaysia** [comment]
yes, but many editor use spaces but not tab, and they will replace it. edit CMakeLists is not so easy

**Pull request merged**
