### PR TITLE
Fix the XCode job never failing because of piping xcodebuild output

### PR DESCRIPTION
**Pull request by viciious**
Some minor cleanup while I'm at it

### CODE REVIEW

**Comment by mikke89** [comment]
Do you know why valgrind started complaining with this change?

**Comment by mikke89** [comment]
No sorry, I see it was a previous change of mine :)

**Comment by viciious** [comment]
Let's see if it works again after the rebase ;)

**Comment by mikke89** [comment]
Thanks for this, and good catch by valgrind ;)

**Pull request merged**
