### PR TITLE
Vulkan for RmlUi

### PR DESCRIPTION
**Pull request by wh1t3lord**
Vulkan for RmlUi!

Firstly, I need to finish this pull request. 

I opened it in order to keep this pull request visible for users who wanted/started wrote their own implementation.

I will implement for **_win32_** only because I don't have enough time to test on different platforms.

Using files from other projects:
https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator - MIT License
https://github.com/KhronosGroup/SPIRV-Reflect - Apache-2.0 License

### CODE REVIEW

**Comment by diamondhat** [comment]
@mikke89 I want to warn you that your architecture use only width and height for rendering texture (I mean what backend needs to know about how to generate textures and etc). But in Vulkan realities, you need to know how much memory you need to allocate in order to represent your texture to GPU. Thus the user must provide information about an 'upload' size of your texture and in that case, we need to change the API calls which have RenderInterface.

So I saw your codebase and for calculating uploading size for texture you use width * height * 4, but that's normal for our examples. But for real examples, the user wants to use different textures with different formats and that causes the changes into our formula like width * height * different_format_which_is_not_4_bytes (e.g. VK_FORMAT_BC1_RGB_SRGB_BLOCK and others). 

But there's one important thing if a user has his own implementation of Vulkan it's all okay if he wants to use our implementation and base his engine somehow on it or you want to support different textures or formats that will cause changes in API. 

It's only a warning. If we just need to run our examples on Vulkan, so all is fine and we can do that without any changes in architecture and API at all.

**Comment by mikke89** [comment]
We always generate textures with RGBA using 1 byte per channel per pixel, so the texture size is well known. If users want to apply compression or use another texture format they have to do that conversion themselves, I don't see this as a reason to change the API.

**Comment by diamondhat** [comment]
@mikke89 I don't call to change the API, but I described what we have and what we would have if we wanted to support new features like new formats or etc. 👍🏻

**Comment by mikke89** [comment]
Hi! Thanks for your work on this, I see that it's been quite some time without updates now.

Do you intend to keep working on this? Otherwise, I think it is time to close this.

With that said, it would be great if you could offer some closing words. In particular, I wonder how far do you feel you got to a finished solution? Any suggestions for anyone else trying to make a Vulkan backend for RmlUi?

I am still interested in seeing a Vulkan implementation. If anyone wants to contribute I suggest that they start on the `backends` branch, which I intend to merge into master for the next major version of RmlUi. That branch attempts to re-organize the way samples and backends are coupled together, paving the way to mix and match renderers and platforms in a re-usable way, and making all samples work on all backends.

**Comment by wh1t3lord** [comment]
@mikke89 Hi!

I've been busy for a while, so I can keep working. I just thought someone would join the development when I had downtime.

**Comment by wh1t3lord** [comment]
@mikke89 I have like one, two free days and I can waste them on it to finish some stuff. Because I come really close to that thing, I hope I can finish and get some results, get the rendering hello world at least.

**Comment by wh1t3lord** [comment]
The current state is:

1. Vulkan is working well;
2. Resizing is not working well; (idk, but two guessings, like we didn't update uniform member 'translate' or somewhere in OnResize method something doesn't update at all);
3. Needs to change the VkDescriptorSet model. Like we need to use only one VkDescriptorSet instance for rendering.

**Comment by mikke89** [comment]
Great work on getting things up and rendering! Appreciate your continued work on this.

**Comment by wh1t3lord** [comment]
Resizing is working well, but now we have bugs with rendering treeview and invaders examples. Seems like you can merge this branch, but it is better to finish all things and merge.

**Comment by wh1t3lord** [comment]
Now allocation is fixed. So we need to think how to resolve those rendering bugs and we are done with Vulkan :)

**Comment by mikke89** [comment]
Hey, thanks and good job!

As we discussed, I've ported the code over to the new backends architecture. See the `vulkan` branch (commit https://github.com/mikke89/RmlUi/commit/531b2c97663af9ac65447aa16ead2048e02698b7). There are still some rendering issues and warnings that need to be resolved before we can merge with master, but I'm happy a lot of things are rendering well. You can continue to work off of the new branch if you'd like, and make a new pull request against that one.

Currently, only the SDL platform is supported together with the Vulkan renderer. To use this backend, set the CMake configuration `SAMPLES_BACKEND=SDL_Vulkan`.

**Comment by wh1t3lord** [comment]
@mikke89 okay I will create a new pull request based on new RmlUI with vulkan branch so I close this one.

**Pull request closed without merging**
