### PR TITLE
Lottie support, but very raw state

### PR DESCRIPTION
**Pull request by diamondhat**
Need to be fixed: 
1. Properly load file (idk how to fix that, because we operate json file), hardcoded file path for default loading. 
2. Create sample project. Temporary I changed loaddocument project and it loads lottie.rml file as example.
3. Color interpretation.
4. Check cmake file and properly connect library (hardcoded path it's not right solution)
5. Fix updating texture without allocation every frame a new texture (just write information, but don't needed to allocate physically "new" texture if resize haven't done)
6. Updating attributes, like 'src', 'width', 'height'.

Done: 
1. Connected lottie as submodule
2. Working lottie library
3. Rendering
4. Custom tag <lottie></lottie>

I am done here, and can't support further (maybe I can add fixes for color interpretation sometime though).

### CODE REVIEW

**Comment by mikke89** [comment]
Thanks for this! Will need some changes before we merge into master. But I can take over from here.

Some changes I intend to to before merging (in addition to your list):

- Move the element out of the core library, add it as a plugin in the sample project.
- Will not use submodules, rather let users handle dependencies themselves.

**Comment by mikke89** [comment]
There will be no changes to the core library, as I intend to move that element out and into the sample as a plugin, so it won't do anything unless you manually copy over the plugin. Does that ease your concern? :)

Otherwise, I'm willing to discuss everything before I merge it to master.

**Comment by mikke89** [comment]
By the way, @diamondhat, do you have a source and a license for the lottie animation you included?

**Comment by rokups** [comment]
I do not really have a preference where integration lives. Just in what form it manifests. But maybe there is no cause for concern. We have `` and its fine.. I no longer know which would be better :)

**Comment by mikke89** [comment]
I think it makes more sense as an element, rather than a decorator, especially since it has intrinsic size. Plus, I think this is the easiest way to update it regularly.

**Comment by diamondhat** [comment]
@mikke89 I used json animations from rlottie repo, and guessed it's all by MIT license. I don't think they are used commercial animations to publish them by MIT license xD

But you can check this file https://github.com/Samsung/rlottie/blob/master/COPYING

**Pull request merged**
