### PR TITLE
Allow templates at any element

### PR DESCRIPTION
**Pull request by Dakror**
Templates are very limited currently, so this change allows any element to include a template thus also providing a functionality of combining modular files

### CODE REVIEW

**Comment by mikke89** [comment]
Thanks for the PR!

I like the idea, and it would be a nice addition to the library. I have some questions and comments here:

- Is the header part of the template included in the document header? Does it happen once for each template, or every time we include a template? These things need to be documented.
- The body handler shouldn't check for "body" tag. This might not always be used.
- Only nodes using the default handler can have a template here. This may be unexpected in some cases.
- It's not entirely clear to me what actually happens when a template gets injected. We should document this with an example and resulting document structure.

I think a lot of this can more easily be handled by introducing a node handler for eg. a `<template>` tag. Then, it should work such that this tag is replaced by all the contents inside the `<body>` of the template, excluding the actual body element. Then any contents inside the `<template>` element is added to the designated content part inside the template.

We should add some unit tests to make sure everything works out as expected.

**Comment by Dakror** [comment]
Introducing this new `<template>` tag would deprecate the current functionality though wouldn't it? I tried to make as small of an edit.

**Comment by mikke89** [comment]
Oh you're right, we already use template for that. How about `<include template="name">`? If we want to include source directly, that element would be a natural point to extend this functionality later as well.

**Comment by Dakror** [comment]
I've reworked the feature by introducing the `<include>` element and its own xml handler. Regarding your questions, yes the header is included since we invoke all of the standard template cache functionality causing the template header to get merged into the source header, and this merging is only invoked when parsing the `<link>` elements in the header.

**Comment by mikke89** [comment]
Great, I like this a lot, thank you!

I can see the usefulness of moving the attributes to the template child. On the other hand, it is a bit unexpected once we suddenly add another element to the template. Maybe we should just add it to all the top-level elements? I'm fine with this any way you choose here :)

I discovered one issue while writing a few unit tests: The attributes of the template body gets added to the body element, even when it's just used as an include. I think it should only be added when used on the document body.
You can test it with this: https://github.com/mikke89/RmlUi/blob/8b633d68455477d851fe9d6c5eb2b42d076d04c8/Tests/Source/UnitTests/Template.cpp

**Comment by Dakror** [comment]
Thanks, I'll look into it. Do you want me to commit the unit case on the branch too?

**Comment by mikke89** [comment]
You can add the commit if you want, or I can add it later so the authorship doesn't get mixed. I'm fine with it either way :)

Also thinking about another related long-standing issue. The document body has their attributes overwritten with the attributes from the template. Eg. if template body has a `class` attribute, then any classes defined on document body are removed. 

It would be great if we could add a warning when this happens. I know it has silently broken my styles before, probably happened to others as well. This would also apply to template children attributes if you choose to implement this.

**Comment by Dakror** [comment]
Actually exactly this behaviour of the XMLNodeHandlerBody is causing the failure of the unit test as well. since in the included file the body causes the original document's body attributes to change.

**Comment by mikke89** [comment]
I see, good work, thanks a lot!

I'm not sure I like warning about duplicates in `Element::SetAttributes`. In many cases this is expected behavior. Instead, I suggest we move that check to the body node handler.

Then if you are happy with this, I'll merge it :)

**Comment by mikke89** [comment]
Awesome, thanks!

**Pull request merged**
