### PR TITLE
Add support for external font providers

### PR DESCRIPTION
**Pull request by viciious**
Work in progress, please do not merge yet.

### CODE REVIEW

**Comment by viciious** [comment]
This is mostly complete but a few shortcuts had to be taken to make this compile and work:
- The naming of FontSubsystemInterface sucks but a bad/temporary name is better than no name at all ;)
- I don't know how FontEffects are supposed to be passed to FontSubsystemInterface::GenerateLayerConfiguration():

https://github.com/mikke89/RmlUi/pull/42/files#diff-4d28679d0d0218bf685aa5107fe88af6L392

https://github.com/mikke89/RmlUi/blob/43528b438c7287bf832127876abe7c7ee926e844/Source/Core/FontSubsystemInterfaceDefault.cpp#L68

- The Debugger plugin depends on the builtin FreeType front-provider; never used the debugger myself so I have little care for it and have no idea on how to fix it in optimal manner:
https://github.com/mikke89/RmlUi/pull/42/files#diff-9453bcb468aafd148a4fbed28e5ddd32L280

- The SDL flag to define RMLUI_NO_FONT_INTERFACE_DEFAULT and drop the FreeType dependency is yet to be added

**Comment by mikke89** [comment]
Awesome work! Thanks for this!

I'll have a closer look at this later. Some brief comments:

- How about just FontInterface for name? :)
- I think we can drop the Bitmap interface now, a custom provider is probably more suited for that case. What do you think?

I can take care of the font effects again once merged. Yeah, not sure how to load the debugger without a default font interface. Maybe just try to use the one the user provides (if the default does not exist), with no guarantees attached?

**Comment by viciious** [comment]
> 
> 
> Awesome work! Thanks for this!
> 
> I'll have a closer look at this later. Some brief comments:
> 
>     * How about just FontInterface for name? :)
> 

This one sounds like an interface for a single Font object or something.

>     * I think we can drop the Bitmap interface now, a custom provider is probably more suited for that case. What do you think?
>

Yeah, I guess so. The positive thing about the current implementation is that stock font effects are reused. In case of an external provider, the author will have to take care of that too.
 
>
> I can take care of the font effects again once merged. Yeah, not sure how to load the debugger without a default font interface. Maybe just try to use the one the user provides (if the default does not exist), with no guarantees attached?

Perhaps the debugger could take a font family name as constructor parameter? But then the builtin RCSS would also need some patching...

**Comment by mikke89** [comment]
> This one sounds like an interface for a single Font object or something.

Right, maybe FontProviderInterface?

> Yeah, I guess so. The positive thing about the current implementation is that stock font effects are reused. In case of an external provider, the author will have to take care of that too.

Yeah, what we could do is turn the current BitmapFont sample into a sample for a custom font provider. Would serve as a good example and if people want to use it they can just copy it or modify it to suit their needs.

> Perhaps the debugger could take a font family name as constructor parameter? But then the builtin RCSS would also need some patching...

Sounds like a good solution to me.

**Comment by viciious** [comment]
> Right, maybe FontProviderInterface?

Considered this one too, but then the existing FontProvider classes would need to be renamed to something else because the new class serves as a facade for both FaceProvider and FontFaceHandle, with bits of FontDatabase on top.

> Yeah, what we could do is turn the current BitmapFont sample into a sample for a custom font provider. 

Sounds like a good idea but that's gonna require a good bit of code refactoring, which I'm not really up for :P

**Comment by mikke89** [comment]
I see. Okay, a new proposal: FontEngineInterface?

Yeah, let's leave the BitmapFont alone for now, and maybe I'll get around to it _some day_  :)

**Comment by viciious** [comment]
> I see. Okay, a new proposal: FontEngineInterface?

Yeah, I like this one :)

**Comment by mikke89** [comment]
How do you feel this is coming along?

I've had a closer look now. First of all, thanks for all the nice work!
I have some comments and questions:

- I feel like the two `LoadFontFace` functions should be exposed to Rml::Core, e.g.   `Rml::Core::GetFontSubsystemInterface()->LoadFontFace("…")`   ->   `Rml::Core::LoadFontFace("…")`.  These are the only two functions (as far as I can tell) that the user will need to interact with.
- It would be a lot cleaner if we just removed the default font source files in CMake, and avoid using the macro in every file. Perhaps move the default implementation to their own folder?
- I think the comments for the functions in the interface should be written from the point of view of somebody implementing the interface. The default interface implementation could briefly summarize what it actually does, like how it is written now but without repeating the arguments, and removing comments on the trivial getters.
- Could we make the debugger use the first loaded font family by default? Maybe allow setting the document font size as well, and use 'rem' values for the rest?
- And finally we still need to rename to FontEngineInterface :)

Also, I want to let you know the changes I intend to do with regards to fonts in the library.

- Implement lazy loading of unicode glyphs. Allow setting a "fallback" font if the current glyph is not in the current font, e.g. a fallback font for emojis.
- Remove BitmapFont: When we do lazy loading of unicode glyphs, these implementations will probably diverge and I don't want to do twice the work. Plus, we can quite substantially clean up the default font engine. Perhaps move some helper functions into a utilities file to ease custom implementations.
- Use UTF8 internally everywhere. Only convert to UTF-16 outside the library when interacting with Windows API. The given FontEngine should be responsible for converting to unicode points. Provide helper methods for this.

**Comment by mikke89** [comment]
You can enable the font effects again like this: 4272fcfbd3438193306c7189fb8bf6fa81b251ee

**Comment by viciious** [comment]
> How do you feel this is coming along?
> 
> I've had a closer look now. First of all, thanks for all the nice work!

No problem! I'm happy to be able to contribute something substantial.

> I have some comments and questions:
> 
>     * I feel like the two `LoadFontFace` functions should be exposed to Rml::Core, e.g.   `Rml::Core::GetFontSubsystemInterface()->LoadFontFace("…")`   ->   `Rml::Core::LoadFontFace("…")`.  These are the only two functions (as far as I can tell) that the user will need to interact with.
> 

Well, I don't know, to be honest I don't have an opinion on this. Why would the user want to interact with them? The library lazily does all the font loading anyway.

>     * It would be a lot cleaner if we just removed the default font source files in CMake, and avoid using the macro in every file. Perhaps move the default implementation to their own folder?

Yes, but I haven't figured out how to do that - going with the macro route seemed like a quicker option compared to fiddling with CMake arrays and whatnot.

> 
>     * I think the comments for the functions in the interface should be written from the point of view of somebody implementing the interface. The default interface implementation could briefly summarize what it actually does, like how it is written now but without repeating the arguments, and removing comments on the trivial getters.

Yeah, I kinda skipped that part for the time being - I'm really lazy when it comes to documenting things :(

> 
>     * Could we make the debugger use the first loaded font family by default? Maybe allow setting the document font size as well, and use 'rem' values for the rest?

I wish it was that easy! I don't really like the way I hacked my way through the Debugger but I can't think of a better solution right now.

Perhaps, another API call to list all available fonts?

> 
>     * And finally we still need to rename to FontEngineInterface :)
> 

Yes, of course :)
I had just spent so much time renaming and moving things around I didn't want to get on to that right way :)

> 
> Also, I want to let you know the changes I intend to do with regards to fonts in the library.
> 
>     * Implement lazy loading of unicode glyphs. Allow setting a "fallback" font if the current glyph is not in the current font, e.g. a fallback font for emojis.

That's what we did for our font provider. The implementation isn't trivial, you can trust me on that!

> 
>     * Remove BitmapFont: When we do lazy loading of unicode glyphs, these implementations will probably diverge and I don't want to do twice the work. Plus, we can quite substantially clean up the default font engine. Perhaps move some helper functions into a utilities file to ease custom implementations.

Well, it's your call here :)
I never cared for it in the first place.

> 
>     * Use UTF8 internally everywhere. Only convert to UTF-16 outside the library when interacting with Windows API. The given FontEngine should be responsible for converting to unicode points. Provide helper methods for this.

Another thing still missing is font effects export...

**Comment by mikke89** [comment]
> No problem! I'm happy to be able to contribute something substantial.

I'm happy to see them :)

> Well, I don't know, to be honest I don't have an opinion on this. Why would the user want to interact with them? The library lazily does all the font loading anyway.

I'm not sure I understand what you mean. This is where the user specifies where the font files are located right? E.g. as in `Shell.cpp`.

> Yes, but I haven't figured out how to do that - going with the macro route seemed like a quicker option compared to fiddling with CMake arrays and whatnot.

Alright, I could perhaps take a look at it later if I feel like burying myself in CMake :P

> Yeah, I kinda skipped that part for the time being - I'm really lazy when it comes to documenting things :(

No worries :)

> I wish it was that easy! I don't really like the way I hacked my way through the Debugger but I can't think of a better solution right now.
> 
> Perhaps, another API call to list all available fonts?

Yup, either that or we could make it so that an empty font-family returns a default font? Either sounds good to me.

Also a less hacky solution might be to use SetProperty after loading the document. I'm not sure though, as we might get warnings about no font found? Although, it will probably work if we do the empty font-family is default font.

> > * Implement lazy loading of unicode glyphs. Allow setting a "fallback" font if the current glyph is not in the current font, e.g. a fallback font for emojis.
> 
> That's what we did for our font provider. The implementation isn't trivial, you can trust me on that!

I didn't want to know this :( Hah, yeah, I can imagine.

> Another thing still missing is font effects export...

What do you mean with the font effects export, did you see my previous post?

**Comment by viciious** [comment]
> I'm not sure I understand what you mean. This is where the user specifies where the font files are located right? E.g. as in `Shell.cpp`.

Oh, I must have forgotten that you had to preload all fonts in libRocket/libRml before using them. In my FontProvider implementation, the LoadFace call does absolutely nothing :)

> Although, it will probably work if we do the empty font-family is default font.

Well, another idea is to use some fake font family name for Debugger such as "Debugger Font" to ensure and rely on the font provider implementation to provide a sensible fallback for missing fonts. Implementations may even choose to override/alias such fake font names.

> What do you mean with the font effects export, did you see my previous post?

Yeah, I just did! Sorry for the confusion - happens when you're both writing your posts simultaneously :)

**Comment by mikke89** [comment]
> Oh, I must have forgotten that you had to preload all fonts in libRocket/libRml before using them. In my FontProvider implementation, the LoadFace call does absolutely nothing :)

Right, I see. We kind of need it for default yes :)

> Well, another idea is to use some fake font family name for Debugger such as "Debugger Font" to ensure and rely on the font provider implementation to provide a sensible fallback for missing fonts. Implementations may even choose to override/alias such fake font names.

Yeah, I like this idea. If we want to follow the naming style of the debugger it would be e.g. `rmlui-debug-font`.

> Yeah, I just did! Sorry for the confusion - happens when you're both writing your posts simultaneously :)

Great :)

**Comment by viciious** [comment]
Please see if you like what I did in 0c6677fd4dea128c8f8cf079f615eefd86b73e93

**Comment by mikke89** [comment]
I like it!

**Comment by viciious** [comment]
I think we don't need this API call anymore:

> bool FontDatabaseDefault::LoadFontFace(const String& file_name, const String& family, Style::FontStyle style, Style::FontWeight weight)

I can't think of any possible use for it, what do you think?

**Comment by mikke89** [comment]
Yeah, I'm fine with removing it.

**Comment by viciious** [comment]
Ok, the only thing left here is to change the documentation to suit your taste :)

**Comment by mikke89** [comment]
Awesome! If you like, I can do the documentation after the merge :)

**Comment by viciious** [comment]
To be honest I’d rather prefer you did it because I can’t stare at this code any minute longer and you do the rest of it anyway

**Comment by mikke89** [comment]
Hah! Thanks for your sacrifices!

I'll take care of it then :)

**Comment by viciious** [comment]
Nah, no problem at all! Is there anything you want to be done before merging?

**Comment by mikke89** [comment]
Just wondering, did you end up keeping the debugger font?

**Comment by viciious** [comment]
No, it’s gone now. For my own application I’m using droid sans, and samples that come with the library use whatever font is loaded first.

**Comment by mikke89** [comment]
Thanks again! Very much appreciated :)

Looks like the Font file wasn't actually removed for some reason? I can do it though, but maybe have a last look to see if some other changes are missing?

**Comment by viciious** [comment]
> 
> 
> Thanks again! Very much appreciated :)
> 
> Looks like the Font file wasn't actually removed for some reason? I can do it though, but maybe have a last look to see if some other changes are missing?

This is weird because I can clearly remember removing the font file.. Nothing else seems to be missing. I'll create a follow up PR if I find anything.

**Pull request merged**
