### PR TITLE
Ignore curly brackets inside string literals in data expressions

### PR DESCRIPTION
**Pull request by Dakror**
Data expressions like {{ 'test {} with format library' }} currently dont work with libraries like fmt, because curly braces inside the string trigger an error. This PR fixes this.

### CODE REVIEW

**Comment by Dakror** [comment]
I'm currently integrating sprintf as a function for data expressions (in combination with my i18n strings) based on the fmt lib. 
I guess you wouldn't want to add a dependency, but when I'm done i could send a PR. It involves defining a formatter for the Variant type

**Comment by Dakror** [comment]
While the test passes, my application doesn't, so hold on :D

**Comment by mikke89** [comment]
Thanks!

I think it makes more sense to move `in_string` as an out parameter into `XMLParseTools::ParseDataBrackets` and do this parsing there. Also, is `DataViewText::Initialize` affected by this? Maybe we want to use the same `XMLParseTools::ParseDataBrackets` in there?

Your translation stuff sounds cool, I'd love to see more of it. We wouldn't want fmt as a core dependency, could it be integrated into the databinding sample perhaps?

**Comment by Dakror** [comment]
The issue definitely is the variant type and non-variadic printf-usage. That's why i had to use the fmt library.

**Review by mikke89 — COMMENTED** [review]
Thanks!

Looks good to me, only there is an issue with the `XMLParseTools.cpp` diff, is it the line endings again?

**Comment by Dakror** [comment]
yeah thanks, i dont know why. i have autocrlf off...

**Comment by mikke89** [comment]
I think that should be on if you're on Windows?

**Comment by Dakror** [comment]
oh does it? okay

**Pull request merged**
