### PR TITLE
Automatically test samples in valgrind in Travis

### PR DESCRIPTION
**Pull request by viciious**
This should also aid in finding memory leaks in the library itself

### CODE REVIEW

**Comment by mikke89** [comment]
Looks really nice. So how does this work, it runs every sample with valgrind and looks for memory leaks? It all seems to pass.

I wonder if the samples really start properly, because the SFML and SDL samples can't get a video mode, which I'm guessing is because there is no video output on the server?
I thought there were some memory leaks in the bitmap font provider for example when I went through that lately. But I haven't taken a closer look at it yet.

**Comment by viciious** [comment]
Yeah, it does exactly that. It creates a virtual screen with framebuffer and OpenGL support and runs all samples with 10 seconds timeout. The XRandr warning appears to be harmless.

Reverting 9f340a0c981da117dbfe8fcaee2213be3c94f964 would make the SFML2 sample to fail the valgrind test. You could try that after merging the PR to make sure that it does actually work the way intended :P

As for the bitmap fonts, I'm not even sure that there are any used in the samples.. That might explain the lack of memory leaks.

**Comment by mikke89** [comment]
Sounds good to me :) I think I will try your suggestion.

There is the separate bitmap font sample, but I may also be wrong about the memory leak.

**Comment by mikke89** [comment]
Works well here:
https://travis-ci.com/mikke89/RmlUi/jobs/211868210

Thanks for this!

**Comment by viciious** [comment]
No idea why certain samples are now not passing the checks on the develop branch :(
Probably has got something to do with the failing video mode setting but I'm not entirely sure.

**Comment by mikke89** [comment]
Yeah, I have no idea what's going on. For some reason the context is not initialized.

**Comment by viciious** [comment]
The context may actually be initialized but then become partially uninitialized due to SetActiveClipRegion setting the properties to uninitialized values? That's just a theory.

**Comment by mikke89** [comment]
Oh, I think you might be right. See ElementUtilities.cpp line 254-258. It might be possible that the uninitialized variables get set on the context, at least it's not easy to see that it cannot.

**Comment by viciious** [comment]
Please try adding --track-origins=yes to valgrind options, that might shed some light on the problem

**Comment by viciious** [comment]
Didn't help that much :(

**Pull request merged**
