### PR TITLE
Travis CI: Use Ninja instead of Make

### PR DESCRIPTION
**Pull request by jhasse**
Automatically maxes out available CPU cores.

### CODE REVIEW

**Comment by mikke89** [comment]
I don't see a compiler log now, are we sure we are getting compiler warnings with this setup? I'd like to ensure that before merging.

**Comment by jhasse** [comment]
Ninja prints it's status on one line (overriding the previous line), but will print warnings and other output normally when they occur. Hard to explain what I mean, you'll see when you run ninja locally :)

**Comment by mikke89** [comment]
Okay, thanks! I'll trust you on that :)

**Comment by viciious** [comment]
I dunno about this. There's no real speed gain from using ninja yet we have lost the job logs, so what's the point?

**Comment by jhasse** [comment]
The number of parallel jobs was hard-coded for make, so if Travis CI decides to increase their CPU count on the runners there would be a speed gain in using ninja.

What do you need the make output for if I may ask? Note that compiler output is not lost.

**Comment by viciious** [comment]
It's just that there's no performance gain in practice and it's not that Travis has announced they are going to bump the number of cores in any foreseeable future.

Having make output allowed to follow the progress of the job both online and retroactively.

**Comment by jhasse** [comment]
You can still follow the progress of the job online. Again, why would you need it retroactively?

If wanted ninja can print more verbose output with `ninja -v`.

**Pull request merged**
