### PR TITLE
RmlUi samples fixes

### PR DESCRIPTION
**Pull request by barotto**
Hey, working with the samples I noticed that under Linux they won't load their assets unless:
  1. they are `make install`'d and
  2. they are launched from their installation dir and
  3. the installation dir is a subdir of a dir called "Samples" (case sensitive).

This pull request fixes a couple of things:
  1. The animation and transform samples are now properly installed (data files were missing)
  2. under Linux you can now launch the samples from anywhere, provided the exe is still in the Build directory or they have been installed with `make install`.

**Note**: 
  * this has not been tested under Windows nor macOS. I will gladly add fixes in case this pull req. breaks the samples for those OS's but I can't test them.
  * under Windows and macOS the samples root directory is still hardwired to "Samples", some user of those OS's should provide a fix for that (see FindSamplesRoot() in Samples/shell/src/win32/ShellWin32.cpp)

### CODE REVIEW

**Comment by mikke89** [comment]
Thanks!

Working fine for me on Windows, except for the invaders sample missing some textures (luainvaders works fine though). See `Game.cpp` Line 83. Have not tested SDL/SFML/DirectX samples. I'd appreciate if someone could test it also on MacOS.

I think it makes sense to use the Samples directory as our main relative path for the samples. However, I'm not sure why we use the path relative to the executable rather than the working directory. I guess this is considered more stable, as IDEs and such can do different things with working directories?

There is no proper equivalent of `make install` on Windows, so I'm not sure what you are proposing to do here? 

One change I'd like to see is putting the CMakeLists file in the root directory, and guide the users to output to `<root>/build/` or `/bin/`, this seems to be a more common approach these days. Then, for what I understand, most compilers will output the executables to e.g. `<root>/build/Debug/`?

**Comment by barotto** [comment]
> Thanks!
> 
> Working fine for me on Windows, except for the invaders sample missing some textures (luainvaders works fine though). See `Game.cpp` Line 83. Have not tested SDL/SFML/DirectX samples. I'd appreciate if someone could test it also on MacOS.

Oops, missed that. I'll re-check all to be sure.

> I think it makes sense to use the Samples directory as our main relative path for the samples. However, I'm not sure why we use the path relative to the executable rather than the working directory. I guess this is considered more stable, as IDEs and such can do different things with working directories?

I guess under Windows it doesn't make much of a difference, as you usually double click on an exe and the working dir ends to be the exe position, but in unix environments it's commong to be inside a command line shell and the current working dir could be anything (e.g.: your home dir).
Reading the executable path will give you a certain, easy position from which to start looking for the assets.

Also consider that under Linux executables and libs are compiled inside Build, whereas under Windows they are put inside a subdir like Build\Release or Build\Debug (if I'm not mistaken), so I'm trying to make the samples work in various situations.

> There is no proper equivalent of `make install` on Windows, so I'm not sure what you are proposing to do here?

`make install` moves libs, executables and all their assets into the designated directory that you choose in the configuration phase (`cmake .`). This can be a systemwide path, like `/usr`, or a local directory that you can then use to create a distribution package.

Once you do `make install` the structure of the installed files ends to be like this:
rmlui-install

The final structure is made compatible with the intended position of libs and executables inside the `/usr` system directory.

> One change I'd like to see is putting the CMakeLists file in the root directory, and guide the users to output to `<root>/build/` or `/bin/`, this seems to be a more common approach these days. Then, for what I understand, most compilers will output the executables to e.g. `<root>/build/Debug/`?

I'm not a cmake expert but every project I've dealt with makes you create a `build` dir and then `cmake ..` inside of it. They add instructions like these in the docs:
```
mkdir build
cd build
cmake ..
## fix dependency issues
make
make install
```

So yes, It's common to have CMakeLists in the root.

**Comment by mikke89** [comment]
Thanks for the thorough explanation, as you can tell, I'm not very familar with Linux development.

The Windows and MacOS versions should work like before as far as I can tell, at least on Windows I think we might as well keep the hardwired path. If somebody wants to improve the MacOS version later that's all good, but for now I think this is ready for merging.

**Comment by barotto** [comment]
> at least on Windows I think we might as well keep the hardwired path.

Yes, I think at least for Windows this should work as you don't usually install libs and samples, you dl a zip and extract it somewhere, but on Linux it's common to have an installation procedure.
I would like to see RmlUi distributed as a system lib on various Linux distributions, but for that to happen things like these need to be solved first. Would be nice to simply do like:
```
$ apt-get install rmlui rmlui-dev rmlui-docs rmlui-samples
```
so that you can tell users to "just install rmlui" instead of "git clone rmlui, cmake, make ...."

**Comment by mikke89** [comment]
I like the ambition, sounds like a good plan :)

**Pull request merged**
