### PR TITLE
Fix Lua object garbage collection bug

### PR DESCRIPTION
**Pull request by slipher**
Disclaimer: this fix has only been tested with our 2-year-old version of the library.

### CODE REVIEW

**Comment by mikke89** [comment]
Thanks for upstreaming this fix!

This reminds me a lot about the discussion here: https://github.com/mikke89/RmlUi/issues/216. If not the same issue, then at least very similar.

What do you think about the proposed (and merged) solution there-in? Do you think that solution already fixes the issue you have? And if not, could you comment on whether there could be any conflict between these two fixes.

I did run and do some basic testing with this change, and everything seems to work fine, however these issues can be hard to reproduce so it would be nice to hear your thoughts.

**Comment by DolceTriade** [comment]
We did cherry pick that change prior to this one and we could still reproduce the crash. Maybe our platform (Google's NaCl runtime) is more prone to the aggressive pointer location reuse but we had a 100% repro that we can use to verify fixes if you'd like 😁.

That fix is insufficient because it only fixes the case where the pointer is reused once before the original non gc object is gc'd. But if it's reused twice and the original object is gc'd before the 2nd object is sets the DNT table to true, we would still crash

**Comment by illwieckz** [comment]
I confirm I reproduce the crash on current RmlUi master but I don't managed to reproduce the bug once I cherry-picked this commit on current RmlUi master.

I used @DolceTriade's branch to port Unvanquished to latest RmlUi version to reproduce the crash on master and test the fix on master:

- https://github.com/Unvanquished/Unvanquished/pull/2027

**Comment by mikke89** [comment]
Thanks guys! Sounds good to me, that is more than enough to justify this change.

Appreciate the pull request.

**Pull request merged**
