### PR TITLE
Make Tabs work with structural data views like data-for

### LINKED ISSUE #173: Tabs do not support data-for
When i try to use something like 

```
<tabset>
<tab data-for="tabs">
<img data-attr-sprite="it.sprite" />
</tab>
...
</tabset>
```

It gives me an error about it.sprite not existing in the data model.

### PR DESCRIPTION
**Pull request by Dakror**
Fixes #173

Copy-paste of the default handler's elementdata method into tabset

### CODE REVIEW

**Comment by mikke89** [comment]
Thanks for the PR. Although I'm generally a bit worried about combining `data-for` with tabsets. The issue is that the tabset changes the structure of the document, which does not always work well with `data-for`. This is also an issue with some other elements such as `select`.

I guess you have tested this more than me at this point, so if this change makes it all work, then that is great :)

Before accepting this though, I'd like to see very thorough testing, so we can declare that tabsets work with data bindings. To start with, that it works to change the number of elements in the input array, and having that reflected in the document. And also that there are no surprises with data views in tabs and inside panels, in particular when combined with `data-for`.

**Comment by Dakror** [comment]
Yeah im currently working on my screen that uses this generated tabset. if i find issues i will report accordingly.

**Comment by Dakror** [comment]
Test Results
- Deletion
  - Deleting an element from the list of tabs: **works**
  - Deleting currently selected element from the list of tabs: **works** 
    - Selects next tab or none when `old selection index >= new size` -> Should retain old selection and account for index change
- Insertion:
  - push_back: **broken**
    - Duplicates newly inserted tab at last and second to last position, deleting previous last tab
  - insert at start: **broken**
    - Same as with push_back but with 1st and 2nd element
  - insert in the middle: **works**
- Insert & Delete
  - Delete newly inserted element: **works**
  - Delete element after newly inserted element: **works**
  - Delete element before newly inserted element: **works**

**Comment by Dakror** [comment]
Closed because there are many issues and a simple tab pane is very easily built using RCSS instead of using the tabset element family.

**Comment by mikke89** [comment]
Thanks for looking into this, I've made a note about tabset incompatibility in the documentation.

**Pull request closed without merging**
