### PR TITLE
Databinding with const

### PR DESCRIPTION
**Pull request by Dakror**
I've revived the old branch from about a year ago since this has started to become really important for my project. Wanting to use a std set in databinding is only possible with const support due to the iterators.

I think i've resolved all of the leftover issues from the initial implementation, and am now testing this within my project.

### CODE REVIEW

**Comment by Dakror** [comment]
Discovering a few loose ends here still, as expected. Will update accordingly

**Comment by mikke89** [comment]
Alright, let me know when you want me to take a look at it again.

**Comment by mikke89** [comment]
I wonder if there isn't a better approach to supporting std sets? I wasn't really enthusiastic about this whole approach, it's kind of quirky. Also, I generally landed on the philosophy of users adapting their data structures to our library, rather than the other way around, for reasons I'm sure we have discussed before :)

**Comment by Dakror** [comment]
True a different approach could be to build specific definitions for sets / maps with a const key or entry inside of it. I might give that a go. Maybe all of this can be solved in userland, where if you want a const or something container you need to write a custom definition..

**Comment by mikke89** [comment]
Yeah, I'm certainly interested to see if there is a way like that. That would be great. I'd prefer we started a new PR if you do come up with a new solution.

**Comment by Dakror** [comment]
will do.

**Pull request closed without merging**
