### PR TITLE
Creating files for releases

### PR DESCRIPTION
**Pull request by mikke89**
I'd like to automate the process of making releases on GitHub whenever we add a new tag. 

First of all, we need to decide what kind of files we would like to include in a release. Some suggestions:

1. Full copy of repository (with source code and assets).
2. Runnable sample binaries for Windows. What about Linux and macOS?
3. Static and dynamic binaries for Windows. What about Linux and macOS?
   - With header files or full source code?
   - Include `Debug` and `Release` builds for RmlCore, RmlControls, RmlDebugger.
4. Full source with Visual Studio projects, no binaries.

What do you think, which of these could be useful? Any other suggestions?

How useful even are binaries for a project like this? I think generally, you'd like to build the files using the compiler used for your project, but perhaps something like `4.` is easier to get going for some new users. But they would still need FreeType which might be confusing. For Linux and macOS building should be simpler already.

Currently, we have an appveyor artifact producing number `2.` for Windows. For `3.` there are separate archives produced for the Debug/Release and Static/Dynamic combinations. Does anyone know if it is possible to combine these into a single archive, or do we have to do this manually for each release?

### CODE REVIEW

**Comment by viciious** [comment]
Cool stuff!
Some thoughts on the points above.

1. Combine with 4 maybe?
2. Runnable binaries for Linux and especially the macOS are going to be problematic, mostly due to dependencies. I would rather not bother.
3. Dynamic libraries and static libraries with headers (not full source code) in a separate archive. Again, I would not rather bother with Linux or macOS - the compilers and stdlibs may differ across systems, the libraries are rather huge (especially the debug ones), etc. In general, the benefits of providing binaries for those systems aren't worth the hassle.

It is possible to combine both debug and release builds in one archive in appveyor if you give up the interface that appveyor provides for automation and fully script your builds instead (pseudoscript follows):

```
cmake -DBUILD_TYPE=RELEASE
msbuild Build/Rocket.sln
7z Release/stuff archive.zip
cmake clean
cmake  -DBUILD_TYPE=DEBUG
msbuild Build/Rocket.sln
7z Release/stuff archive.zip
```

**Comment by mikke89** [comment]
Thanks! That's great feedback. Okay, no Linux and macOS binaries. I'll look into scripted builds, looks like a good start.

The problem I see with 4. is the freetype dependency. If we provide the project files then the freetype headers/library need to be copied in to a specific (undocumented) location by the user.

Thinking about it some more, the binary files are also problematic with FreeType in mind as the user would need to link with the proper dll (same as we built with?).

One possible solution is to create one single Windows binaries archive with full source, binaries, project files, and freetype header/libraries.

**Comment by mikke89** [comment]
I feel quite happy now with the current approach.

So I decided to go for one big zip archive for each build platform (providing both win32 and win64). Each archive includes both static and dynamic libraries, sample binaries to easily try them out, full sample source (as they could be helpful to look at), header files, as well as the freetype library.

Thus, they include all you need to link up the library and hack away :)

I presume the GitHub release will link to the full source code for those who prefer to build from source.

If somebody wants to have a look at the result, and test that everything is working for them, have a look at the produced [x64 artifact here](https://ci.appveyor.com/api/buildjobs/x1gxbvlyhmx79t4e/artifacts/RmlUi-win64.zip) and let me know if you have any feedback.

**Comment by viciious** [comment]
Umm, so this only for tagged github releases? Quite frankly, bundling all this stuff for regular commits looks like an overkill to me. I really don't want to download the 30mb archive in case I want to check the state of the library or some new feature, thus I'd appreciate if you would keep the way artifacts work for non-tagged commits.

**Comment by viciious** [comment]
> What are you really looking for there, trying out the demos? 

Well, I guess you could put it that way too.

**Comment by mikke89** [comment]
I've added a separate archive for samples now. Does it look good to you?

**Comment by viciious** [comment]
> 
> 
> > What are you really looking for there, trying out the demos?
> 
> Well, I guess you could put it that way too.

Yup! All samples seem to run fine too.

**Comment by mikke89** [comment]
Awesome!

**Pull request merged**
